set(TCLTK_MAJOR 8)
set(TCLTK_MINOR 6)
set(TCLTK_PATCH 1)
set(TCLTK_VERSION ${TCLTK_MAJOR}.${TCLTK_MINOR}.${TCLTK_PATCH})
set(TCLTK_URL ${LLNL_URL})
set(TCL_GZ tcl${TCLTK_MAJOR}.${TCLTK_MINOR}.${TCLTK_PATCH}-src.tar.gz)
set(TK_GZ tk${TCLTK_MAJOR}.${TCLTK_MINOR}.${TCLTK_PATCH}-src.tar.gz)
set(TCL_MD5 aae4b701ee527c6e4e1a6f9c7399882e)
set(TK_MD5 63f21c3a0e0cefbd854b4eb29b129ac6)
# Two sources here, need to fake it
set(TCLTK_SOURCE "${TCLTK_URL}/${TCL_GZ} ${TCL_MD5}")
set(TCLTK_MD5 "${TCLTK_URL}/${TK_GZ} ${TK_MD5}")

if (CDAT_BUILD_ESGF)
    add_cdat_package(TclTk "" "" "")
else()
    add_cdat_package_dependent(TclTk "" "" ON "CDAT_BUILD_GUI" OFF)
endif()
